apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: secret-01
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: secret-01
              key: password
      ports:
        - containerPort: 80