# Para Maquinas simples sin restauracion
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: MI_VARIABLE
      value: "Mi variable"
    - name: MI_VARIABLE_2
      value: "Mi variable 2"
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    resources:
      requests:
        cpu: "200m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 1
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    ports:
    - containerPort: 80
